#!/bin/bash
# generated by ll-helper

STARTUP=$(cat $PREFIX/share/applications/*.desktop | grep '^Exec=' | head -n 1 | sed 's/^Exec=//g' | xargs -n 1 echo 2>/dev/null | head -n 1)
REBASED_STARTUP=$(echo $STARTUP | sed -E -e "s#/opt/apps/\S+/files#${PREFIX}#g" -e "s+/usr+$PREFIX+g")
echo STARTUP: ${STARTUP}
echo REBASED_STARTUP: ${REBASED_STARTUP}
echo BOOT: ${LINGLONG_COMMAND}
sed -i -E $PREFIX/share/applications/*.desktop -e "/Exec=/ s#/opt/apps/\S+/files#${PREFIX}#g" -e "/Exec=/ s+/usr+$PREFIX+g" -e "/Exec=/ s+$REBASED_STARTUP+$LINGLONG_COMMAND+g"

if od "$REBASED_STARTUP" -An -N2 -tx2 | grep -q "2123"; then
    echo Patch Script: ${STARTUP}
    sed -i -E -e "s#/opt/apps/\S+/files#${PREFIX}#g" "$REBASED_STARTUP"
fi

echo "exec ${REBASED_STARTUP} \$@" >>$LINGLONG_COMMAND
chmod +x $LINGLONG_COMMAND
